/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Server;

import db.CommonFunction;
import java.awt.Color;
import java.awt.Container;
import java.sql.Connection;
import java.sql.ResultSet;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pratik
 */
public class DeactivatedExams extends javax.swing.JFrame {

    /**
     * Creates new form DeactivatedExams
     */
     Connection cnn;
    CommonFunction cf=new CommonFunction();
    public void readData() throws Exception
    {
        ResultSet rst=cf.getResultset("course");
        cname.removeAllItems();
        while(rst.next())
        {
           cname.addItem(rst.getString("cname")); 
        }
        
    }
    
    public void fillData(String query)
    {
        try{
           
            DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        while(model.getRowCount()>0)
       {
           model.removeRow(model.getRowCount()-1);
       }
          
        ResultSet rst1=cf.getResultset(query);
        if(rst1.next())
        {
            do{
               
           model.addRow(new Object[]{rst1.getString("eid"),rst1.getString("totalq"),rst1.getString("dur"),rst1.getString("max"),rst1.getString("pass"),rst1.getString("date"),rst1.getString("quetype"),"Activate","Change Questions"});
             
            
       }while(rst1.next());
        } 
       }catch(Exception ee)
       {
           System.out.println(ee);
       }
    }
   
    public void fillTable()
    {
         String query="";
         
            if(cname.getSelectedIndex()!=-1)
            {
             query="exam where state='Deactivate' and date>=curdate() and cname='"+cname.getSelectedItem()+"' and ";
            }
       if(sname.getSelectedIndex()!=-1)
       {
           if(sname.getSelectedItem().toString().equals("All")==false)
               
           query=query+" sname='"+sname.getSelectedItem()+"' and ";
       }
       
       if(query.length()==0)
           return;
       query=query.substring(0,query.lastIndexOf(" and "));
       
       fillData(query);
       
       System.out.println(query);
    }
    public void ReadData1(String cname)
    {try{
        ResultSet rst=cf.getResultset("subject where cid='"+cname+"'");
        sname.removeAllItems();
       sname.addItem("All");
       while(rst.next())
       {
           sname.addItem(rst.getString("sname"));
       }
       
      
       fillTable();
       
    }catch(Exception ee)
    {
        System.out.println("Exception In ReadData1"+ee);
    }
    }
    
      public DeactivatedExams(String cname1,String sname1) throws Exception
      {
          initComponents();
          
         
      }
    public DeactivatedExams() {
        initComponents();
        try{
             Container ctx=getContentPane();
             ctx.setBackground(new Color(150,255,255));
            readData();
        }catch(Exception ee)
        {
            System.out.println("Exception is"+ee);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        cname = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        sname = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Exam ID", "Total Questions", "Duration", "Maximum", "Minimum", "Date", "Type", "Activation", "Change Questions"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Course");

        cname.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cnameItemStateChanged(evt);
            }
        });
        cname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnameActionPerformed(evt);
            }
        });

        jLabel2.setText("Subject");

        sname.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                snameItemStateChanged(evt);
            }
        });

        jButton1.setText("Show All Result");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(cname, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sname, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(88, 88, 88))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cnameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cnameItemStateChanged
        try{
            
            if(cname.getSelectedIndex()!=-1)
            {
            String cname1=cname.getSelectedItem().toString();
              ReadData1(cname1);
              fillTable();
            }
          
            //          ShowResult showResult = new ShowResult(cname1);
            //          showResult.setVisible(true);
        }catch(Exception ee)
        {
            System.out.println("Exception is"+ee);
        }
    }//GEN-LAST:event_cnameItemStateChanged

    private void snameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_snameItemStateChanged
        try{
           fillTable();
        }catch(Exception ee)
        {
            System.out.println("Subject Chnaged Exception"+ee);
        }
    }//GEN-LAST:event_snameItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            //        String sname1=sname.getSelectedItem().toString();
            //        String cname1=cname.getSelectedItem().toString();
            //        readData2(sname1,cname1);
            String query="exam where state='Deactivate' and date>=curdate()";
            
            fillData(query);

            
    
        }catch(Exception ee)
        {
            System.out.println("Exception in Button"+ee);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        try{
            
           int rowidx=jTable1.getSelectedRow();
           int colidx=jTable1.getSelectedColumn();
           if(colidx==7)
           {
            DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
            int id=Integer.parseInt(model.getValueAt(rowidx, 0).toString());
           // dispose();
           ChangeStatus frm=new ChangeStatus(this,id);
           frm.setVisible(true);
           }
           else if(colidx==8)
           {
             QuestionList frm=new QuestionList();
             frm.setVisible(true);
             frm.cname.setSelectedItem(this.cname.getSelectedItem());
           }
       }catch(Exception ee)
       {
           System.out.println("Exception is"+ee);
       }
    }//GEN-LAST:event_jTable1MouseClicked

    private void cnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cnameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeactivatedExams.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeactivatedExams.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeactivatedExams.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeactivatedExams.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeactivatedExams().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cname;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> sname;
    // End of variables declaration//GEN-END:variables
}
