/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Server;

import db.CommonFunction;
import java.awt.Color;
import java.awt.Container;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pratik
 */
public class ExamConduction extends javax.swing.JFrame {

    /**
     * Creates new form ExamConduction
     * @param lst
     * @param time1
     */
 ArrayList lst1=new ArrayList();
 ExamPaperSet frm;
     public ExamConduction(String time1,ArrayList lst)
    {
        initComponents();
         Container ctx=getContentPane();
             ctx.setBackground(new Color(150,255,255));
        //this.frm=frm;
        this.lst1=lst;
        try{
            for(Object m:lst)
            {
                int idx=(int)m;
                System.out.println(""+idx);
               // lst1.add(idx);
                type.setText(""+time1);
            rs=cf.getResultset("exam where eid="+idx);
            
            DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
            if(rs.next())
            {   
                 model.addRow(new Object[]{rs.getString("eid"),rs.getString("cname"),rs.getString("sname"),rs.getString("state")}); 
            }
            
            
            }  
          
        }catch(Exception ee)
        {
           System.out.println("Change Status Error"+ee); 
        }
    }
    
    
    public ExamConduction(int rowidx,String status)
    {
        initComponents();
        try{
            System.out.println(""+status);
             DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
            // ResultSet rst=cf.getResult("question where eid);
            ResultSet rst=cf.getResultset("exam where eid="+rowidx);
             if(rst.next())
             {
                 
                 model.addRow(new Object[]{rst.getString("eid"),rst.getString("cname"),rst.getString("sname"),rst.getString("state")});
             }
            
             
//model.setValueAt(status,row,9);
            
            
        }catch(Exception ee)
        {
            System.out.println("Exception in Exam Parameter Conduction"+ee);
        }
    }
    public ResultSet rs;
    CommonFunction cf=new CommonFunction();
    public ExamConduction() {
        initComponents();
        try{
            rs=cf.getResultset("exam");
           
            DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
            setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            while(rs.next())
            { 
              //if(rs.getString("state").equals("Deactivate"))
              model.addRow(new Object[]{rs.getString("eid"),rs.getString("cname"),rs.getString("sname"),rs.getString("state")});  
            }
            
        }catch(Exception ee)
        {
            System.out.println("Exception in ExamConduction"+ee);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        type = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Exam iD", "Course Name", "Subject Name", "Status"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Type");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(jLabel1)
                .addGap(99, 99, 99)
                .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
       
        try{
            int rowindex=jTable1.getSelectedRow();
        
       int columnindex=jTable1.getSelectedColumn();
        DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
       Object state1=model.getValueAt(rowindex,columnindex);
       System.out.println("State 1"+state1);
//        if(JOptionPane.showMessageDialog()==)
 if(JOptionPane.showConfirmDialog(this,"Surely Want to Edit ?")==JOptionPane.OK_OPTION)
 {
     
 
       
       String state=model.getValueAt(rowindex,columnindex).toString();
       int id=Integer.parseInt(model.getValueAt(rowindex,0).toString());
       String type1=type.getText();     
//Paper V=new Paper();
       //V.setEid(id);
      // V.setTime(state);
    // String type1=type.getText();
   dispose();
   
//       ChangeStatus frm=new ChangeStatus(state,id,rowindex,type1);
//       frm.setVisible(true);
ChangeStatus frm=new ChangeStatus(this,id,state,rowindex,lst1);
     frm.setVisible(true);
model.removeRow(rowindex);
System.out.println("Hello");
         
           // dispose();
       
 }
 else{
     
 }
        }catch(Exception ee)
        {
            System.out.println("Error in Exam Conduction"+ee);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExamConduction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExamConduction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExamConduction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExamConduction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExamConduction().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField type;
    // End of variables declaration//GEN-END:variables
}
