/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Server;

import db.CommonFunction;
import java.awt.Color;
import java.awt.Container;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.StringTokenizer;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pratik
 */
public class FormA extends javax.swing.JFrame {

    /**
     * Creates new form FormA
     */int rowindex=0;
    CommonFunction cf=new CommonFunction();
  Paper V;
   String sname1=null;
    public ResultSet rst;
    public FormA(Paper V,ConductExam frm){
        initComponents();
        try{
            this.frm=frm;
        System.out.println("Id is"+V.getCname());
         DefaultTableModel model= (DefaultTableModel)jTable1.getModel();
        eid1.setText(""+V.getEid());
        cname.setText(V.getCname());
        sname.setText(V.getSname());
        totalq.setText(""+V.getTotalq());
        quetype.setText(V.getType());
        dur.setText(""+V.getDur());
        maxm.setText(""+V.getMax());
        passm.setText(""+V.getPass());
        date.setText(V.getDate());
        rst=cf.getResultset("question where sid='"+V.getSname()+"' order by rand() limit "+V.getTotalq());
        
       // V.setCname((String)model.getValueAt(1, 0));
       // sname=(String)model.getValueAt(1, 0);
        while(rst.next())
        {
             model.addRow(new String[]{rst.getString(1),rst.getString(2),rst.getString(3),rst.getString(4),rst.getString(5),rst.getString(6),rst.getString(7)});
            
             
             
             
             
        }
        rowindex=model.getRowCount();
        System.out.println("Rows"+rowindex);
        //V.setSname(rst.getString("sid"));
        }
        catch(Exception ee)
        {
        }
       
        //psmt1.setString(9,V.getType());
    }
    public Paper readData(Paper V)
           {
               return V;
           }
    PreparedStatement psmt1,psmt2;
    ConductExam frm=new ConductExam();
  public FormA()
  {
      initComponents();
      try{
          this.frm=frm;
           Container ctx=getContentPane();
             ctx.setBackground(new Color(150,255,255));
//          Connection cnn=db.MyConnection.getConnection();
//      psmt1=cnn.prepareStatement("insert into exam values(?,?,?,?,?,?,?,?,?)");
//       psmt2=cnn.prepareStatement("insert into examquestion values(?,?)");
//        V=new Paper();
//        System.out.println("Result Set"+V.getCname());
//        V.setCname(rst.getString(1));
//        V.setSname(rst.getString(2));
        
      }catch(Exception ee)
      {
          
          System.out.println("Exception is"+ee);
      }
      
  }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cname = new javax.swing.JTextField();
        sname = new javax.swing.JTextField();
        totalq = new javax.swing.JTextField();
        quetype = new javax.swing.JTextField();
        dur = new javax.swing.JTextField();
        maxm = new javax.swing.JTextField();
        passm = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        eid1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        date = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Subject Name", "Question No.", "Question", "Option A", "Option B", "Option C", "Option D"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("CREATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Course");

        jLabel2.setText("Subject");

        jLabel3.setText("Total Questions");

        jLabel4.setText("Type");

        jLabel5.setText("Duration");

        jLabel6.setText("Max Marks");

        jLabel7.setText("Passing Marks");

        totalq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalqActionPerformed(evt);
            }
        });

        quetype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quetypeActionPerformed(evt);
            }
        });

        jLabel8.setText("Exam Id");

        jLabel9.setText("Date");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cname)
                    .addComponent(sname)
                    .addComponent(eid1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(totalq)
                    .addComponent(quetype)
                    .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(134, 134, 134)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dur)
                    .addComponent(maxm)
                    .addComponent(passm, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(totalq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(eid1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(quetype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(maxm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(sname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel9)
                        .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(passm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       try
           {
                Connection cnn=db.MyConnection.getConnection();
      psmt1=cnn.prepareStatement("insert into exam values(?,?,?,?,?,?,?,?,?,?)");
       psmt2=cnn.prepareStatement("insert into examquestion values(?,?)");
               psmt1.setInt(1,Integer.parseInt(eid1.getText()));
               psmt1.setString(2,cname.getText());
               psmt1.setString(3,sname.getText());
               psmt1.setInt(4,Integer.parseInt(totalq.getText()));
               psmt1.setInt(5,Integer.parseInt(dur.getText()));
               psmt1.setInt(6,Integer.parseInt(maxm.getText()));
               psmt1.setInt(7,Integer.parseInt(passm.getText()));
              
               System.out.println("Hello");
               StringTokenizer B=new StringTokenizer(date.getText(),"-");
               int y=0,m=0,d=0;
               while(B.hasMoreTokens())
                   {
                       if(y==0)
                         y=Integer.parseInt(B.nextToken())-1900;
                       else if(m==0)
                        m=Integer.parseInt(B.nextToken())-1;
                       else
                         d=Integer.parseInt(B.nextToken());
                   }
               psmt1.setDate(8,new Date(y,m,d));
               psmt1.setString(9,quetype.getText());
                psmt1.setString(10,"Deactivate");
               int count=psmt1.executeUpdate();
               System.out.println("Count is"+count);
               
               
                DefaultTableModel model= (DefaultTableModel)jTable1.getModel();
                
                System.out.println("Row"+rowindex);
                int row=0;
               while(model.getRowCount()>row)
               {
                
               psmt2.setInt(1,Integer.parseInt(eid1.getText()));
               System.out.println("Model "+model.getValueAt(row,1));
               psmt2.setInt(2,Integer.parseInt(model.getValueAt(row,1)+""));
                psmt2.executeUpdate();
               row++;
                       }
              
               if(row==model.getRowCount()-1)
                   System.out.println("Record Successfully Inserted");
               
//                V.setEid(Integer.parseInt(eid1.getText()+1));
              // ConductExam frm=new ConductExam();
               frm.clear();
               int id=Integer.parseInt(eid1.getText());
               //int rows=model.getRowCount();
              //int id;
           //id = Integer.parseInt(model.getValueAt(rows-1,0).toString());
           ++id;
          
               frm.eid.setText(""+id);
//               ConductExam frm1=new ConductExam();
//               frm1.setVisible(true);
               dispose();
               
              
              // System.out.println("Count1 is"+count1);
               
       
               
//             //V=new Paper();
//              //V.setSname(model)
//                DefaultTableModel model= (DefaultTableModel)jTable1.getModel();
//           sname1=(String)model.getValueAt(0, 0);
//           System.out.println(""+sname1);
           
           //System.out.println("Sname is"+V.getSname());
           //rst=cf.getResultset("subject inner join question where subject.sname=question.sid and sname='"+sname1+"'");
          
             //System.out.println(""+V.getCname());
             // 
            // rst=cf.getResultset("question");
              //System.out.println(""+V.getSname());
             // System.out.println(""+rst.getString("sid"));
            // ResultSet rs=cf.getResultset("subject where sname='"+V.getSname()+"'");
//            int id;
//             if(rst.next())
//             {   
//                 String cid; 
//                     cid=rst.getString("cid");
//                 System.out.println(""+cid);
//                 System.out.println(V.getTotalq());
//                 id=1;
//                 
//          psmt1.setInt(1,id);
//                 psmt1.setString(2,cid);
//           
//             psmt1.setString(3,V.getSname());
//            psmt1.setInt(4,V.getTotalq());
//            psmt1.setInt(5,V.getDur());
//            psmt1.setInt(6,V.getMax());
//            psmt1.setInt(7,V.getPass());
//             psmt1.setD(8,V.getDate());
//             psmt1.setString(9,V.getType());
//             
//             int count=psmt1.executeUpdate();
//             
//             System.out.println("Exam Count is"+count);
//             }
            // id++;
       }catch(Exception ee)
       {
           System.out.println("Exception in Create Table is"+ee);
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void quetypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quetypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quetypeActionPerformed

    private void totalqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalqActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cname;
    private javax.swing.JTextField date;
    private javax.swing.JTextField dur;
    private javax.swing.JTextField eid1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField maxm;
    private javax.swing.JTextField passm;
    private javax.swing.JTextField quetype;
    private javax.swing.JTextField sname;
    private javax.swing.JTextField totalq;
    // End of variables declaration//GEN-END:variables
}
