/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Server;

import db.CommonFunction;
import java.awt.Color;
import java.awt.Container;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.StringTokenizer;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pratik
 */
public class FormB extends javax.swing.JFrame {

    /**
     * Creates new form FormB
     */
    CommonFunction cf=new CommonFunction();
    PreparedStatement psmt1,psmt2;
    ConductExam frm=new ConductExam();
    public FormB(Paper V,ConductExam frm)
    {
        initComponents();
       System.out.println("Vector id is"+V.getCname());
        try{
            this.frm=frm;
             Container ctx=getContentPane();
             ctx.setBackground(new Color(150,255,255));
             //Connection cnn=db.MyConnection.getConnection();
             DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
             String query="select * from question where sid='"+V.getSname()+"'";
             
             ResultSet rst=cf.getResult(query);
             System.out.println("Query is"+query);
         //ResultSet rs=cf.getResultset("question where sid='"+V.getSname()+"'");
        // eid.setText("Hello");
          eid2.setText(""+V.getEid());
        course1.setText(V.getCname());
        subject1.setText(V.getSname());
        totalq1.setText(""+V.getTotalq());
        quetype1.setText(V.getType());
        dur1.setText(""+V.getDur());
        max1.setText(""+V.getMax());
        pass1.setText(""+V.getPass());
        date1.setText(V.getDate());
         while(rst.next())
         {  
           //  System.out.println("RS");
            model.addRow(new Object[]{false,rst.getString(1),rst.getString(2),rst.getString(3),rst.getString(4),rst.getString(5),rst.getString(6),rst.getString(7)});
            
         }

         }catch(Exception ee)
        {
            System.out.println("Form B Error "+ee);
        }
    }
    public FormB() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        eid = new javax.swing.JTextField();
        cname = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        sname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        totalq = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        quetype = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        date = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        dur = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        maxm = new javax.swing.JTextField();
        passm = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        eid2 = new javax.swing.JTextField();
        course1 = new javax.swing.JTextField();
        subject1 = new javax.swing.JTextField();
        totalq1 = new javax.swing.JTextField();
        quetype1 = new javax.swing.JTextField();
        date1 = new javax.swing.JTextField();
        dur1 = new javax.swing.JTextField();
        max1 = new javax.swing.JTextField();
        pass1 = new javax.swing.JTextField();

        jLabel8.setText("Exam Id");

        jLabel1.setText("Course");

        jLabel2.setText("Subject");

        jLabel3.setText("Total Questions");

        totalq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalqActionPerformed(evt);
            }
        });

        jLabel4.setText("Type");

        quetype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quetypeActionPerformed(evt);
            }
        });

        jLabel9.setText("Date");

        jLabel5.setText("Duration");

        jLabel6.setText("Max Marks");

        jLabel7.setText("Passing Marks");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "Subject Name", "Question No.", "Question", "Option1", "Option2", "Option3", "Option4"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(10);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(18);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(30);
        }

        jLabel10.setText("Exam Id");

        jLabel11.setText("Course");

        jLabel12.setText("Subject");

        jLabel13.setText("Total Questions");

        jLabel14.setText("Type");

        jLabel15.setText("Date");

        jLabel16.setText("Duration");

        jLabel17.setText("Max Marks");

        jLabel18.setText("Passing Marks");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("CREATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(eid2, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                            .addComponent(course1)
                            .addComponent(subject1))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(totalq1, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                            .addComponent(quetype1)
                            .addComponent(date1))
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dur1, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                            .addComponent(max1)
                            .addComponent(pass1)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 861, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel10)
                            .addComponent(eid2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalq1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel11)
                            .addComponent(course1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(quetype1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dur1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(max1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel18)
                        .addComponent(jLabel12)
                        .addComponent(jLabel15)
                        .addComponent(date1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pass1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(subject1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void totalqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalqActionPerformed

    private void quetypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quetypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quetypeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            Paper V=new Paper();
            Connection cnn=db.MyConnection.getConnection();
        
      psmt1=cnn.prepareStatement("insert into exam values(?,?,?,?,?,?,?,?,?,?)");
       psmt2=cnn.prepareStatement("insert into examquestion values(?,?)");
               psmt1.setInt(1,Integer.parseInt(eid2.getText()));
               psmt1.setString(2,course1.getText());
               psmt1.setString(3,subject1.getText());
               psmt1.setInt(4,Integer.parseInt(totalq1.getText()));
               psmt1.setInt(5,Integer.parseInt(dur1.getText()));
               psmt1.setInt(6,Integer.parseInt(max1.getText()));
               psmt1.setInt(7,Integer.parseInt(pass1.getText()));
               
             //  System.out.println("Hello");
               StringTokenizer B=new StringTokenizer(date1.getText(),"-");
               int y=0,m=0,d=0;
               while(B.hasMoreTokens())
                   {
                       if(y==0)
                         y=Integer.parseInt(B.nextToken())-1900;
                       else if(m==0)
                        m=Integer.parseInt(B.nextToken())-1;
                       else
                         d=Integer.parseInt(B.nextToken());
                   }
               psmt1.setDate(8,new Date(y,m,d));
               psmt1.setString(9,quetype1.getText());
               psmt1.setString(10,"Deactivate");
               int count=psmt1.executeUpdate();
               //System.out.println("Count is"+count);
               
               DefaultTableModel model= (DefaultTableModel)jTable1.getModel();
                
               // System.out.println("Row"+rowindex);
                int row=0;
                
               while(model.getRowCount()>row)
               {
                if((Boolean)model.getValueAt(row, 0))
                {
               psmt2.setInt(1,Integer.parseInt(eid2.getText()));
               //System.out.println("Model "+model.getValueAt(row,1));
               psmt2.setInt(2,Integer.parseInt(model.getValueAt(row,2)+""));
                psmt2.executeUpdate();
              
                }
                 row++;
                       }
              
               if(row==model.getRowCount()-1)
                   System.out.println("Record Successfully Inserted");
               
//               V.setEid(Integer.parseInt(eid2.getText())+1);
//               //System.out.println("Vector is"+V);
//               ConductExam frm=new ConductExam(V);
               frm.clear();
               //int rows=model.getRowCount();
//               
              int id;
           id = Integer.parseInt(eid2.getText());
           ++id;
               frm.eid.setText(""+id);
               dispose();
               
        }catch(Exception ee)
        {
            System.out.println("Exception in Create Button"+ee);
        }
    }//GEN-LAST:event_jButton1ActionPerformed
int count=0;
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        try{
            
        
        DefaultTableModel model= (DefaultTableModel)jTable1.getModel();
        int colindex=jTable1.getSelectedColumn();
       int rowindex=jTable1.getSelectedRow();
       int total=Integer.parseInt(totalq1.getText());
       System.out.println("total questions"+total);
       
       if(colindex==0)
               { 
                   System.out.println("Value is"+model.getValueAt(rowindex, colindex).toString());
                  String sel= model.getValueAt(rowindex, colindex).toString();
                  System.out.println("Selection is"+sel);
                  
                   if(sel.equals("true") && count<total)
                       {
                           
                       ++count;
                       System.out.println("Value of Count is"+count);
                       }
                   else if(sel.equals("true") && count>=total)
                   {
                        JOptionPane.showMessageDialog(this,"You have Already Selected the number of questions you want to Select");
                       model.setValueAt(false, rowindex, colindex);
                   }
                   else if(sel.equals("false"))
                   {
                       count--;
                   }
                           
                    
                   }
                  
                     
               }
//       if(count>=total)
//                      {
//                     
//                       }
       //Paper V=new Paper();
       //System.out.println(""+V.getTotalq());
       
        
        catch(Exception ee)
        {
            System.out.println("Exception in Table "+ee);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cname;
    private javax.swing.JTextField course1;
    private javax.swing.JTextField date;
    private javax.swing.JTextField date1;
    private javax.swing.JTextField dur;
    private javax.swing.JTextField dur1;
    private javax.swing.JTextField eid;
    private javax.swing.JTextField eid2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField max1;
    private javax.swing.JTextField maxm;
    private javax.swing.JTextField pass1;
    private javax.swing.JTextField passm;
    private javax.swing.JTextField quetype;
    private javax.swing.JTextField quetype1;
    private javax.swing.JTextField sname;
    private javax.swing.JTextField subject1;
    private javax.swing.JTextField totalq;
    private javax.swing.JTextField totalq1;
    // End of variables declaration//GEN-END:variables
}
