/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Server;

import db.CommonFunction;
import java.awt.Color;
import java.awt.Container;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pratik
 */
public class GetAttemptedExams extends javax.swing.JFrame {

    /**
     * Creates new form GetAttemptedExams
     */
    public void readData() throws Exception
    {
      ResultSet rs=cf.getResultset("course");
      while(rs.next())
      {
          jComboBox1.addItem(rs.getString("cname"));
      }
    }
    public void readData1(String cname) throws Exception
    {
        ResultSet rs=cf.getResultset("subject where cid='"+cname+"'");
        jComboBox3.removeAll();
        jComboBox3.removeAllItems();
        while(rs.next())
        {
            jComboBox3.addItem(rs.getString("sname"));
        }
    }
    CommonFunction cf=new CommonFunction();
    
    public GetAttemptedExams() {
        initComponents();
        try{
            Container ctx=getContentPane();
            ctx.setBackground(new Color(150,255,255));
           // jPanel1.setBackground(new Color(150,255,255));
            readData();
            ResultSet rs=cf.getResultset("exam");
            DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
            while(rs.next())
            {
                if(rs.getString("state").equalsIgnoreCase("Attempted"))
                model.addRow(new Object[]{rs.getInt("eid"),rs.getString("cname"),rs.getString("sname"),rs.getInt("totalq"),rs.getInt("dur"),rs.getInt("max"),rs.getInt("pass"),rs.getString("quetype"),rs.getDate("date"),rs.getString("state")});
            }
            
        }catch(Exception ee)
        {
            System.out.println("Exception is"+ee);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Course");

        jLabel2.setText("Subject");

        jButton1.setText("Get Attempted Exams");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jCheckBox1.setText("Last Exam");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Exam ID", "Course Name", "Subject Name", "Total Questions", "Duration", "Maximum Marks", "Passing Marks", "Question Type", "Date", "State"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jCheckBox1)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(88, 88, 88)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(112, 112, 112)
                            .addComponent(jLabel2)
                            .addGap(112, 112, 112)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(54, 54, 54)
                            .addComponent(jButton1)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 976, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jButton1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jCheckBox1)
                .addGap(47, 47, 47)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
       try{
           String cname=jComboBox1.getSelectedItem().toString();
           readData1(cname);
           
       }catch(Exception ee)
       {
           System.out.println("Exception is"+ee);
       }
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
           // readData();
           String cname=jComboBox1.getSelectedItem().toString();
           String sname=jComboBox3.getSelectedItem().toString();
           
            ResultSet rs=cf.getResultset("exam where cname='"+cname+"' and sname='"+sname+"'");
            DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
            while(model.getRowCount()>0)
            {
                model.removeRow(model.getRowCount()-1);
            }
            //Date d1=new Date();
//           Date d2=new Date();
//               int day=d2.getDate();
//               int month=d2.getMonth()+1;
//               int year=d2.getYear()+1900;
//               String str="",str1="";
//               if(d2.getDate()<10)
//               {
//                   str="0";
//                   if(d2.getMonth()<9)
//                   {
//                       str1="0";
//                   }
//                   else
//                   {
//                      str1="";   
//                   }
//                }
//               else{
//                   str="";
//                   if(d2.getMonth()<9)
//                   {
//                       str1="0";
//                   }
//                   else{
//                       str1="";
//                   }
//               }
              // System.out.println(""+day+" "+month+" "+year);
              // String date=str+day+"-"+str1+month+"-"+year;
//               String examdate=year+"-"+str1+month+"-"+str+day;
//               System.out.println("Date is"+examdate);
               //d2=new Date(examdate);
//              d2=new SimpleDateFormat("yyyy-MM-dd").parse(examdate);
              //Date date1=new SimpleDateFormat("yyyy-MM-dd").parse(date);
//              System.out.println("Converted Date is"+d2);
               rs.last();
               Date date3=rs.getDate("date");
               System.out.println("Third Date is"+date3);
              int row=0; 
            if(jCheckBox1.isSelected())
            {
                System.out.println("CheckBox is Selected");
                int eid=cf.getMaxId("select max(eid) from exam where cname='"+cname+"' and sname='"+sname+"'");
                System.out.println("Exam ID is "+eid);
                System.out.println("Course Name is "+cname);
                System.out.println("Subject Name is "+sname);
                 ResultSet rst=cf.getResultset("exam where cname='"+cname+"' and sname='"+sname+"' and eid="+eid);

                    
                if(rst.next())
                {

                            model.addRow(new Object[]{rst.getInt("eid"),rst.getString("cname"),rst.getString("sname"),rst.getInt("totalq"),rst.getInt("dur"),rst.getInt("max"),rst.getInt("pass"),rst.getString("quetype"),rst.getDate("date"),rst.getString("state")});

               }

            }
            else{
                System.out.println("CheckBoxx not Selected");
                         rs=cf.getResultset("exam where cname='"+cname+"' and sname='"+sname+"'");
            while(rs.next())
            {
                //System.out.println("Hello");
                if(rs.getString("state").equalsIgnoreCase("Attempted"))
                model.addRow(new Object[]{rs.getInt("eid"),rs.getString("cname"),rs.getString("sname"),rs.getInt("totalq"),rs.getInt("dur"),rs.getInt("max"),rs.getInt("pass"),rs.getString("quetype"),rs.getDate("date"),rs.getString("state")});
            }
            } 
        }catch(Exception ee)
        {
            System.out.println("Exception is"+ee);
        } 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        try{
            DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
            int rowidx=jTable1.getSelectedRow();
            int eid=Integer.parseInt(model.getValueAt(rowidx, 0).toString());
            DeclareExams frm=new DeclareExams(eid);
            frm.setVisible(true);
            
        }catch(Exception ee)
        {
            System.out.println("Get Attempted Exam Table Error"+ee);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GetAttemptedExams.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GetAttemptedExams.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GetAttemptedExams.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GetAttemptedExams.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GetAttemptedExams().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
