/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Server;

import db.CommonFunction;
import java.awt.Color;
import java.awt.Container;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pratik
 */
public class SearchingForm extends javax.swing.JFrame {

    /**
     * Creates new form SearchingForm
     */
    public void readData() throws Exception
    {
//      while(rs.next())
//      {
//          jComboBox1.addItem(rs.getString("id"));
//          jComboBox5.addItem(rs.getString("user"));
//          jComboBox6.addItem(rs.getString("pass"));
//            
//          
//      }
    }
    public void readData1() throws Exception
    { //ResultSet rs1=cf.getResult("select distinct(course) from student order by course");
    
    ResultSet rs1=cf.getResult("select distinct(course),cname from student inner join course where student.course=course.cid order by course");
   // Result rs2=cf.getResultset("")
        while(rs1.next())
        {   
            course.addItem(rs1.getString("cname"));
            //course.addItem(rs1.getString("course"));
            
            
        }
        
    }
     public void readData2() throws Exception
    { ResultSet rs2=cf.getResult("select distinct(session) from student order by session");
        while(rs2.next())
        {
            sess.addItem(rs2.getString("session"));
            
            
        }
        
    }
//      public void readData3() throws Exception
//    {  ResultSet rs3=cf.getResult("select distinct(year) from student");
//        while(rs3.next())
//        {
//            //year.addItem(rs3.getString("year"));
//           
//            
//        }
//        
//    }
    CommonFunction cf=new CommonFunction();
    public ResultSet rs,rs1,rs2,rs3;
    Connection cnn;
    PreparedStatement psmt1,psmt2;
    public SearchingForm() {
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        initComponents();
        try{
          Container ctx=getContentPane();
             ctx.setBackground(new Color(150,255,255));   
        cnn=db.MyConnection.getConnection();
        psmt1=cnn.prepareStatement("select * from student");
        rs=cf.getResultset("student");
        readData();
        
        readData1();
        //rs2=cf.getResult("select distinct(session) from student");
         readData2();
         //rs3=cf.getResult("select distinct(year) from student");
         //readData3();
         rs=cf.getResultset("student");
         DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
            
            while(rs.next())
            {
                model.addRow(new Object[]{rs.getString("ID"),rs.getString("First_Name"),rs.getString("Last_Name"),rs.getString("Course"),rs.getString("Phone"),rs.getString("Address"),rs.getString("Session"),rs.getString("User"),rs.getString("Pass")});   
              
            }
        
         setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        }catch(Exception ee)
        {
            System.out.println("Error is"+ee);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        course = new javax.swing.JComboBox<>();
        sess = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Course");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Session");

        course.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        sess.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "First Name", "Last Name", "Course", "Phone No.", "Address", "Session", "UserName", "Password"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("SEARCH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("SHOW ALL RECORDS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(course, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))
                        .addGap(92, 92, 92)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                            .addComponent(sess, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 975, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(course, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
            String course1=course.getSelectedItem().toString();
            ResultSet rs1=cf.getResultset("course");
            int id=0;
            while(rs1.next())
            {
                if(rs1.getString("cname").equals(course1))
                     id=rs1.getInt("cid");
            }
            String sess1=sess.getSelectedItem().toString();
           // String year1=year.getSelectedItem().toString();
            rs=cf.getResultset("student where course="+id+" and session='"+sess1+"'");
            //int row=0;
            System.out.println("ModelRowCount is"+model.getRowCount());
            while(model.getRowCount()>0)
            {
                model.removeRow(model.getRowCount()-1);
                //row++;
                
            }
            while(rs.next())
            {
                model.addRow(new Object[]{rs.getString("ID"),rs.getString("First_Name"),rs.getString("Last_Name"),rs.getString("Course"),rs.getString("Phone"),rs.getString("Address"),rs.getString("Session"),rs.getString("User"),rs.getString("Pass")});   
                
            }
           // rs.first();
        }
        
        catch(Exception ee)
        {
            System.out.println("Exception in Search Button "+ee);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{
            DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
            System.out.println(""+model.getRowCount());
        ResultSet rst=cf.getResultset("student");
        while(model.getRowCount()>0)
            {
                model.removeRow(model.getRowCount()-1);
                //row++;
                
            }
        while(rst.next())
        {
             model.addRow(new Object[]{rst.getString("ID"),rst.getString("First_Name"),rst.getString("Last_Name"),rst.getString("Course"),rst.getString("Phone"),rst.getString("Address"),rst.getString("Session"),rst.getString("User"),rst.getString("Pass")});
        }
        }catch(Exception ee)
        {
            System.out.println("All Record Error"+ee);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchingForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> course;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> sess;
    // End of variables declaration//GEN-END:variables
}
